UI/Models/TaskModels/TaskViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UI.Models.TaskModels
{
    public class TaskViewModel
    {
        public int Id { get; set; }
        public int UserId { get; set; }

        [Display(Name = "Görev")]
        [Required(ErrorMessage = "Lütfen bir görev giriniz.")]
        public string Task { get; set; }


        [Display(Name = "Açıklama")]
        [Required(ErrorMessage = "Lütfen bir açıklama giriniz.")]
        public string Description { get; set; }


        [Display(Name = "Öncelik")]
        [Required(ErrorMessage = "Lütfen bir 0-255 arasında bir öncelik giriniz.")]
        [Range(0, 255)]
        public byte Priorty { get; set; }


        [Display(Name = "Durum")]
        [Required(ErrorMessage = "Lütfen durumu seçiniz.")]
        public bool Status { get; set; }
    }
}

UI/Models/UserModels/AddUserModel.cs
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UI.Models
{
    public class AddUserModel
    {
        public UserDto User { get; set; }

        public AddUserModel()
        {
            User = new UserDto();
        }
    }
}

UI/Models/UserModels/UserEditModel.cs
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UI.Models
{
    public class UserEditModel
    {
        public UserDto User { get; set; }

        public UserEditModel()
        {
            User = new UserDto();
        }
    }
}

UI/Models/UserModels/UserListModel.cs
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UI.Models
{
    public class UserListModel
    {
        public List<UserDto> Users { get; set; }

        public UserListModel()
        {
            Users = new List<UserDto>();
        }
    }
}

UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

UI/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using DAL;
using DTO;
using UI.Models;
using UI.Models.TaskModels;

namespace UI.Controllers
{
    /*
     * Not: Normalde burada tanımlanan modeller viewmodel olarak tanımlanması gerekiyor. 
     * Ancak kod bütünlüğü sağlamak adına, aynı mimariyi devam ettirdim.
     * 
     */
    public class TaskController : Controller
    {
        private TaskManager _manager;
        private TaskViewModel _model;
        public TaskController()
        {
            _manager = new TaskManager();
            _model = new TaskViewModel();
        }


        #region Index
        public ActionResult Index()
        {
            var taskDtoList = _manager.GetTasks();
            var modelList = new List<TaskViewModel>();

            foreach (var item in taskDtoList)
            {
                var model = new TaskViewModel();

                Mapper.Map(item, model);
                modelList.Add(model);
            }

            ViewBag.Submitted = false;

            return View(modelList);
        }
        #endregion

        #region ListTasks
        public ActionResult TaskList(int userId)
        {
            ViewBag.UserId = userId;

            var taskDtoList = _manager.GetTasks(userId);
            var modelList = new List<TaskViewModel>();

            foreach (var item in taskDtoList)
            {
                var model = new TaskViewModel();

                Mapper.Map(item, model);
                modelList.Add(model);
            }

            ViewBag.Submitted = false;

            return View(modelList);
        }
        #endregion

        #region Add Task

        [HttpGet]
        public ActionResult AddTask(int userId)
        {
            var model = new TaskViewModel();
            model.UserId = userId;

            ViewBag.Submitted = false;

            return View(model);
        }


        [HttpPost]
        public ActionResult AddTask(TaskViewModel model)
        {
            var dto = new UserTaskDto();
            Mapper.Map(model, dto);

            var result = _manager.AddTask(dto);

            ViewBag.Result = result;

            ViewBag.Submitted = true;

            return View(model);
        }
        #endregion

        #region Edit Task

        [HttpGet]
        public ActionResult EditTask(int id)
        {

            var dto = _manager.GetTask(id);

            Mapper.Map(dto, _model);

            ViewBag.Submitted = false;

            return View(_model);
        }

        [HttpPost]
        public ActionResult EditTask(TaskViewModel model)
        {
            var dto = new UserTaskDto();

            Mapper.Map(model, dto);

            var result = _manager.EditTask(dto);

            model.UserId = dto.UserId;
            model.Id = dto.Id;

            ViewBag.Result = result;

            ViewBag.Submitted = true;

            return View(model);
        }
        #endregion

        #region Delete Task
        [HttpGet]
        public ActionResult DeleteTask(int id)
        {
            var dto = _manager.GetTask(id);

            Mapper.Map(dto, _model);

            ViewBag.Submitted = false;

            return View(_model);
        }

        [HttpPost]
        public ActionResult DeleteTask(TaskViewModel model)
        {
            var dto = new UserTaskDto();

            Mapper.Map(model, dto);

            var result = _manager.DeleteTask(dto);

            ViewBag.Result = result;
            ViewBag.Submitted = true;


            model.UserId = dto.UserId;
            model.Id = dto.Id;

            return View(model);
        }
        #endregion
    }
}

UI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.Models;

namespace UI.Controllers
{
    public class UserController : Controller
    {
        #region Index
        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region ListUsers
        public ActionResult UserList()
        {
            DAL.UserManager manager = new DAL.UserManager();
            var result = manager.GetUsers();

            UserListModel model = new UserListModel();
            model.Users = result;
            ViewBag.Submitted = false;
            return View(model);
        }
        #endregion

        #region Add User
        [HttpGet]
        public ActionResult AddUser()
        {
            AddUserModel model = new AddUserModel();
            ViewBag.Submitted = false;
            return View(model);
        }

        [HttpPost]
        public ActionResult AddUser(AddUserModel model)
        {
            DAL.UserManager manager = new DAL.UserManager();
            var result = manager.AddUser(model.User);

            ViewBag.Result = result;
            ViewBag.Submitted = true;
            return View();
        }
        #endregion

        #region Edit User
        [HttpGet]
        public ActionResult EditUser(int id)
        {
            DAL.UserManager manager = new DAL.UserManager();
            UserEditModel model = new UserEditModel();
            model.User = manager.GetUser(id);
            ViewBag.Submitted = false;
            return View(model);
        }
        [HttpPost]
        public ActionResult EditUser(UserEditModel model)
        {
            DAL.UserManager manager = new DAL.UserManager();
            var result = manager.EditUser(model.User);

            ViewBag.Result = result;
            ViewBag.Submitted = true;
            return View();
        }
        #endregion

        #region DeleteUser
        public ActionResult DeleteUser(int id)
        {
            DAL.UserManager manager = new DAL.UserManager();
            var result = manager.DeleteUser(id);

            ViewBag.Result = result;
            ViewBag.Submitted = true;
            return View();
        }
        #endregion
    }
}

UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AGBLab Interview Sample 1</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Kullanıcılar", "UserList", "User")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AGMLab</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

UI/Views/Task/AddTask.cshtml
@model UI.Models.TaskModels.TaskViewModel

@{
    ViewBag.Title = "AddTask";
}

<h2>Yeni Görev Ekle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <p>
        @if (ViewBag.Submitted)
        {
            // If the form was submitted
            if (ViewBag.Result)
            {
                @Html.Label("İşlem başarıyla gerçekleşti");

            }
            else
            {
                @Html.Label("İşlem sırasında hata oluştu!");
            }
        }
    </p>

    if (ViewBag.Result == null || ViewBag.Result == false)
    {
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Task, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Task, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Task, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Priorty, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Priorty, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Priorty, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Status)
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

}

<div>
    @Html.ActionLink("Listeye Dön", "TaskList", new { userId = Model.UserId })
</div>

UI/Views/Task/DeleteTask.cshtml
,@model UI.Models.TaskModels.TaskViewModel

@{
    ViewBag.Title = "DeleteTask";
}

<h2>Görev Sil</h2>


<p>
    @if (ViewBag.Submitted)
    {
        // If the form was submitted
        if (ViewBag.Result)
        {
            @Html.Label("İşlem başarıyla gerçekleşti");

        }
        else
        {
            @Html.Label("İşlem sırasında hata oluştu!");
        }
    }
</p>

@if (ViewBag.Result == null || ViewBag.Result == false)
{
    <h3>Bu görevi silmek istediğinizden emin misiniz?</h3>
    <div>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Task)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Task)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Priorty)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Priorty)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Sil" class="btn btn-default" /> |
                @Html.ActionLink("Listeye Dön", "TaskList", new { userId = Model.UserId })
            </div>
        }
    </div>
}
else
{
    @Html.ActionLink("Listeye Dön", "TaskList", new { userId = Model.UserId })
}

UI/Views/Task/EditTask.cshtml
@model UI.Models.TaskModels.TaskViewModel

@{
    ViewBag.Title = "EditTask";
}

<h2>Görevi Düzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <p>
        @if (ViewBag.Submitted)
        {
            // If the form was submitted
            if (ViewBag.Result)
            {
                @Html.Label("İşlem başarıyla gerçekleşti");

            }
            else
            {
                @Html.Label("İşlem sırasında hata oluştu!");
            }
        }
    </p>

    if (ViewBag.Result == null || ViewBag.Result == false)
    {
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Task, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Task, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Task, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Priorty, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Priorty, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Priorty, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Status)
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
}

<div>
    @Html.ActionLink("Listeye Dön", "TaskList", new { userId = Model.UserId })
</div>

UI/Views/Task/Index.cshtml
@model IEnumerable<UI.Models.TaskModels.TaskViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Tüm Görevler</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId) <br />
           (İşlem kolaylığı açısından <br />
             id gösteriyorum sadece)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Task)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Priorty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Task)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Priorty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
    </tr>
}

</table>

UI/Views/Task/TaskList.cshtml
@model IEnumerable<UI.Models.TaskModels.TaskViewModel>

@{
    ViewBag.Title = "TaskList";
}

<h2>Görev Listesi</h2>

<p>
    @Html.ActionLink("Yeni Görev Ekle", "AddTask", new { userId = ViewBag.UserId})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Task)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Priorty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Task)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Priorty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "EditTask", new { id = item.Id }) |
                @Html.ActionLink("Sil", "DeleteTask", new { id = item.Id })
            </td>
        </tr>
}

</table>

UI/Views/User/AddUser.cshtml
@model UI.Models.AddUserModel
@{
    ViewBag.Title = "AddUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">

        <form method="post">
            <div class="row">
                <div class="col-md-2">Adı</div>
                <div class="col-md-9">@Html.TextBoxFor(x => x.User.Name)</div>
            </div>
            <div class="row">
                <div class="col-md-2">Soyadı</div>
                <div class="col-md-9">@Html.TextBoxFor(x => x.User.Surname)</div>
            </div>
            <div class="row">
                <div class="col-md-2">Adresi</div>
                <div class="col-md-9">@Html.TextBoxFor(x => x.User.Address)</div>
            </div>
            <div class="row">
                <div class="col-md-2">Eposta</div>
                <div class="col-md-9">@Html.TextBoxFor(x => x.User.Email)</div>
            </div>
            <div class="row">
                <div class="col-md-2">Telefon Numarası</div>
                <div class="col-md-9">@Html.TextBoxFor(x => x.User.MobileNumber)</div>
            </div>
            <div class="row">
                <div class="col-md-2">Şifre</div>
                <div class="col-md-9">@Html.PasswordFor(x => x.User.Password)</div>
            </div>
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-9"><input type="submit" value="Save" /></div>
            </div>

        </form>

        <p>
            @if (ViewBag.Submitted)
            {
                // If the form was submitted
                if (ViewBag.Result)
                {  
                    @Html.Label("İşlem başarıyla gerçekleşti");

                }
                else
                {
                    @Html.Label("İşlem sırasında hata oluştu!");
                }
            }
        </p>
    </div>
</div>

UI/Views/User/DeleteUser.cshtml
@{
    ViewBag.Title = "DeleteUser";
}

<p>
    @if (ViewBag.Submitted)
    {
        // If the form was submitted
        if (ViewBag.Result)
        {
            @Html.Label("İşlem başarıyla gerçekleşti");

        }
        else
        {
            @Html.Label("İşlem sırasında hata oluştu!");
        }
    }
</p>

UI/Views/User/EditUser.cshtml
@model UI.Models.UserEditModel
@{
    ViewBag.Title = "EditUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-md-12">

        <form method="post">
            <div class="row">
                <div class="col-md-2">Adı</div>
                <div class="col-md-9">@Html.TextBoxFor(x => x.User.Name)</div>
            </div>
            <div class="row">
                <div class="col-md-2">Soyadı</div>
                <div class="col-md-9">@Html.TextBoxFor(x => x.User.Surname)</div>
            </div>
            <div class="row">
                <div class="col-md-2">Adresi</div>
                <div class="col-md-9">@Html.TextBoxFor(x => x.User.Address)</div>
            </div>
            <div class="row">
                <div class="col-md-2">Eposta</div>
                <div class="col-md-9">@Html.TextBoxFor(x => x.User.Email)</div>
            </div>
            <div class="row">
                <div class="col-md-2">Telefon Numarası</div>
                <div class="col-md-9">@Html.TextBoxFor(x => x.User.MobileNumber)</div>
            </div>
            <div class="row">
                <div class="col-md-2">Şifre</div>
                <div class="col-md-9">@Html.PasswordFor(x => x.User.Password)</div>
            </div>
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-9"><input type="submit" value="Save" /></div>
            </div>
            @Html.HiddenFor(x=> x.User.Id)
        </form>

        <p>
            @if (ViewBag.Submitted)
            {
                // If the form was submitted
                if (ViewBag.Result)
                {
                    @Html.Label("İşlem başarıyla gerçekleşti");

                }
                else
                {
                    @Html.Label("İşlem sırasında hata oluştu!");
                }
            }
        </p>
    </div>
</div>

UI/Views/User/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

UI/Views/User/UserList.cshtml
@model UI.Models.UserListModel
@{
    ViewBag.Title = "UserList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-md-2"><p>
    @Html.ActionLink("Yeni Kullanıcı Ekle", "AddUser")
</p></div>
</div>
<div class="row">
    <div class="col-md-12">
        <table style="width:80%">
            <tr>
                <td style="width:25%">Adı</td>
                <td style ="width:25%">Soyadı</td>
                <td style ="width:20%">Görevler</td>
                <td style="width:15%">Düzenle</td>
                <td style="width:15%">Sil</td>

            </tr>
            @foreach (var item in Model.Users)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Surname</td>
                    <td>@Html.ActionLink("Görevler", "TaskList", "Task", new { userId = @item.Id }, new { })</td>
                    <td>@Html.ActionLink("Düzenle", "EditUser", new { id = @item.Id })</td>
                    <td>@Html.ActionLink("Sil", "DeleteUser", new { id = @item.Id })</td>
                </tr>
            }

        </table>
    </div>
</div>